pub struct Plus(f32);
pub struct Minus(f32);
pub struct MinusPercentage(f32);
pub struct PlusPercentage(f32);
pub struct Multiply(f32);

#[allow(non_camel_case_types)]
#[derive(Debug)]
pub enum StatType {
    flail_critical_strike_multiplier_Plus(Plus(f32)),
    support_gem_limit_Plus(Plus),
    map_bossing_difficulty_Plus(Plus(f32)),
    map_expedition_chest_marker_count_Plus(Plus(f32)),
    map_pinnacle_boss_difficulty_Plus(Plus(f32)),
    minion_critical_strike_multiplier_Plus(Plus(f32)),
    spell_skill_gem_level_Plus(Plus(f32)),
    all_skill_gem_quality_Plus(Plus(f32)),
    chaos_skill_gem_level_Plus(Plus(f32)),
    maps_with_bosses_additional_essence_Plus(Plus(f32)),
    grenade_skill_cooldown_count_Plus(Plus(f32)),
    map_breach_domain_difficulty_Plus(Plus(f32)),
    map_simulacrum_difficulty_Plus(Plus(f32)),
    map_voodoo_king_difficulty_Plus(Plus(f32)),
    base_critical_strike_multiplier_Plus(Plus(f32)),
    ignites_apply_fire_resistance_Plus(Plus(f32)),
    quarterstaff_critical_strike_multiplier_Plus(Plus(f32)),
    one_handed_melee_critical_strike_multiplier_Plus(Plus(f32)),
    bow_critical_strike_multiplier_Plus(Plus(f32)),
    cold_skill_gem_level_Plus(Plus(f32)),
    gain_Percent_maximum_energy_shield_as_freeze_threshold_Plus(Plus(f32)),
    base_spell_critical_strike_multiplier_Plus(Plus(f32)),
    attack_critical_strike_multiplier_Plus(Plus(f32)),
    crossbow_critical_strike_multiplier_Plus(Plus(f32)),
    all_skill_gem_level_Plus(Plus(f32)),
    critical_strike_multiplier_vs_enemies_on_full_life_Plus(Plus(f32)),
    base_thorns_critical_strike_multiplier_Plus(Plus(f32)),
    map_logbook_difficulty_Plus(Plus(f32)),
    critical_strike_multiplier_with_dagger_Plus(Plus(f32)),
    maps_with_bosses_additional_shrine_Plus(Plus(f32)),
    melee_range_Plus(Plus(f32)),
    maps_with_bosses_additional_strongbox_Plus(Plus(f32)),
    base_mana_cost_MinusPercent(MinusPercentage(f32)),
    base_self_freeze_duration_MinusPercent(MinusPercentage(f32)),
    base_self_ignite_duration_MinusPercent(MinusPercentage(f32)),
    energy_shield_delay_MinusPercent_when_not_on_full_life(MinusPercentage(f32)),
    base_self_shock_duration_MinusPercent(MinusPercentage(f32)),
    base_self_critical_strike_multiplier_MinusPercent(MinusPercentage(f32)),
    energy_shield_delay_MinusPercent(MinusPercentage(f32)),
    energy_shield_delay_MinusPercent_if_stunned_recently(MinusPercentage(f32)),
    staff_attack_area_of_effect_PlusPercent(PlusPercentage(f32)),
    cold_damage_PlusPercent(PlusPercentage(f32)),
    one_handed_attack_speed_PlusPercent(PlusPercentage(f32)),
    damage_while_dual_wielding_PlusPercent(PlusPercentage(f32)),
    non_damaging_ailment_effect_PlusPercent_with_critical_strikes(PlusPercentage(f32)),
    map_strongbox_mod_effect_PlusPercent(PlusPercentage(f32)),
    allies_in_presence_attack_speed_PlusPercent(PlusPercentage(f32)),
    support_anticipation_charge_gain_frequency_PlusPercent(PlusPercentage(f32)),
    fire_damage_PlusPercent(PlusPercentage(f32)),
    knockback_distance_PlusPercent(PlusPercentage(f32)),
    accuracy_rating_PlusPercent_equal_to_Percent_attack_critical_strike_chance(PlusPercentage(f32)),
    cast_speed_PlusPercent_when_on_low_life(PlusPercentage(f32)),
    spell_damage_PlusPercent_if_have_crit_recently(PlusPercentage(f32)),
    hit_damage_stun_multiplier_PlusPercent_with_crits(PlusPercentage(f32)),
    one_handed_melee_critical_strike_chance_PlusPercent(PlusPercentage(f32)),
    arrow_critical_strike_chance_PlusPercent_max_as_distance_travelled_increases(
        PlusPercentage(f32),
    ),
    summon_totem_cast_speed_PlusPercent(PlusPercentage(f32)),
    electrocuted_enemy_damage_taken_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_per_warcry_used_recently(PlusPercentage(f32)),
    attack_speed_PlusPercent_per_15_dex(PlusPercentage(f32)),
    axe_damage_PlusPercent(PlusPercentage(f32)),
    map_non_unique_delirium_monsters_splinter_amount_PlusPercent(PlusPercentage(f32)),
    lightning_damage_PlusPercent_while_affected_by_herald_of_thunder(PlusPercentage(f32)),
    atlas_keystone_prefix_or_suffix_mod_effect_PlusPercent_final(PlusPercentage(f32)),
    bow_accuracy_rating_PlusPercent(PlusPercentage(f32)),
    distance_scaled_accuracy_rating_penalty_PlusPercent(PlusPercentage(f32)),
    one_handed_melee_accuracy_rating_PlusPercent(PlusPercentage(f32)),
    cast_speed_PlusPercent_per_num_unique_spells_cast_recently(PlusPercentage(f32)),
    elemental_damage_with_attack_skills_PlusPercent_while_using_flask(PlusPercentage(f32)),
    flask_charges_gained_PlusPercent(PlusPercentage(f32)),
    area_of_effect_PlusPercent_if_have_stunned_an_enemy_recently(PlusPercentage(f32)),
    ignite_effect_on_self_PlusPercent(PlusPercentage(f32)),
    jagged_ground_duration_PlusPercent(PlusPercentage(f32)),
    critical_hit_damage_bonus_PlusPercent_vs_enemies_within_2m_distance(PlusPercentage(f32)),
    map_dropped_maps_rarity_PlusPercent(PlusPercentage(f32)),
    energy_shield_recovery_rate_PlusPercent_if_not_hit_recently(PlusPercentage(f32)),
    spell_damage_PlusPercent_while_wielding_melee_weapon(PlusPercentage(f32)),
    totems_attack_speed_PlusPercent_per_active_totem(PlusPercentage(f32)),
    projectile_damage_PlusPercent_vs_enemies_within_2m_distance(PlusPercentage(f32)),
    map_sanctum_and_ultimatum_key_drop_chance_PlusPercent_in_desert_biome(PlusPercentage(f32)),
    melee_damage_PlusPercent_at_close_range(PlusPercentage(f32)),
    energy_shield_from_helmet_PlusPercent(PlusPercentage(f32)),
    melee_critical_strike_chance_PlusPercent_when_on_full_life(PlusPercentage(f32)),
    evasion_rating_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_vs_enemies_affected_by_status_ailments(PlusPercentage(f32)),
    map_breach_monster_quantity_PlusPercent(PlusPercentage(f32)),
    skill_effect_duration_PlusPercent(PlusPercentage(f32)),
    attack_damage_PlusPercent_when_on_low_life(PlusPercentage(f32)),
    debuff_time_passed_PlusPercent(PlusPercentage(f32)),
    map_expedition_relic_mod_effect_PlusPercent(PlusPercentage(f32)),
    quarterstaff_daze_build_up_PlusPercent(PlusPercentage(f32)),
    attack_skills_damage_PlusPercent_while_holding_shield(PlusPercentage(f32)),
    attack_speed_PlusPercent(PlusPercentage(f32)),
    hit_damage_freeze_multiplier_PlusPercent(PlusPercentage(f32)),
    map_rare_chest_amount_PlusPercent(PlusPercentage(f32)),
    hit_damage_PlusPercent_vs_chilled_enemies(PlusPercentage(f32)),
    attack_and_cast_speed_PlusPercent_with_elemental_skills(PlusPercentage(f32)),
    hit_damage_pin_multiplier_PlusPercent(PlusPercentage(f32)),
    base_elemental_status_ailment_duration_PlusPercent(PlusPercentage(f32)),
    mace_damage_PlusPercent(PlusPercentage(f32)),
    armour_PlusPercent_if_hit_enemy_with_melee_attack_recently(PlusPercentage(f32)),
    cast_speed_PlusPercent_if_have_crit_recently(PlusPercentage(f32)),
    map_boss_dropped_item_quantity_PlusPercent(PlusPercentage(f32)),
    armour_and_evasion_on_low_life_PlusPercent(PlusPercentage(f32)),
    charm_charges_used_PlusPercent(PlusPercentage(f32)),
    warcry_cooldown_speed_PlusPercent(PlusPercentage(f32)),
    base_poison_effect_PlusPercent(PlusPercentage(f32)),
    base_movement_velocity_PlusPercent(PlusPercentage(f32)),
    stun_threshold_PlusPercent_per_rage(PlusPercentage(f32)),
    attack_speed_PlusPercent_if_rare_or_unique_enemy_nearby(PlusPercentage(f32)),
    lightning_damage_PlusPercent(PlusPercentage(f32)),
    charm_effect_PlusPercent(PlusPercentage(f32)),
    chaos_damage_PlusPercent(PlusPercentage(f32)),
    totem_life_PlusPercent(PlusPercentage(f32)),
    block_recovery_PlusPercent(PlusPercentage(f32)),
    movement_speed_PlusPercent_for_4_seconds_on_block(PlusPercentage(f32)),
    map_monster_tre_PlusPercent(PlusPercentage(f32)),
    flask_life_and_mana_to_recover_PlusPercent(PlusPercentage(f32)),
    movement_speed_PlusPercent_if_enemy_killed_recently(PlusPercentage(f32)),
    thorns_damage_PlusPercent(PlusPercentage(f32)),
    maximum_energy_shield_from_body_armour_PlusPercent(PlusPercentage(f32)),
    spear_critical_strike_chance_PlusPercent(PlusPercentage(f32)),
    totem_skill_cast_speed_PlusPercent(PlusPercentage(f32)),
    totem_duration_PlusPercent(PlusPercentage(f32)),
    ascendancy_warbringer_block_chance_PlusPercent_final(PlusPercentage(f32)),
    melee_damage_PlusPercent_vs_immobilised_enemies(PlusPercentage(f32)),
    evasion_rating_PlusPercent_while_surrounded(PlusPercentage(f32)),
    cold_damage_PlusPercent_while_affected_by_herald_of_ice(PlusPercentage(f32)),
    shock_effect_PlusPercent_with_critical_strikes(PlusPercentage(f32)),
    map_expedition_vendor_reroll_currency_quantity_PlusPercent(PlusPercentage(f32)),
    minion_skill_area_of_effect_PlusPercent(PlusPercentage(f32)),
    weapon_swap_speed_PlusPercent(PlusPercentage(f32)),
    minion_reservation_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_if_have_crit_in_past_8_seconds(PlusPercentage(f32)),
    claw_attack_speed_PlusPercent(PlusPercentage(f32)),
    armour_PlusPercent_if_you_havent_been_hit_recently(PlusPercentage(f32)),
    unarmed_attack_skill_melee_dash_range_PlusPercent(PlusPercentage(f32)),
    armour_break_duration_PlusPercent(PlusPercentage(f32)),
    armour_PlusPercent_per_rage(PlusPercentage(f32)),
    base_life_leech_rate_PlusPercent(PlusPercentage(f32)),
    physical_damage_reduction_rating_PlusPercent(PlusPercentage(f32)),
    evasion_PlusPercent_if_hit_recently(PlusPercentage(f32)),
    elemental_damage_PlusPercent_if_enemy_shocked_recently(PlusPercentage(f32)),
    melee_damage_PlusPercent_vs_heavy_stunned_enemies(PlusPercentage(f32)),
    quarterstaff_damage_PlusPercent(PlusPercentage(f32)),
    life_regeneration_rate_PlusPercent_while_stationary(PlusPercentage(f32)),
    skill_speed_PlusPercent(PlusPercentage(f32)),
    base_enemy_critical_strike_chance_PlusPercent_against_self(PlusPercentage(f32)),
    critical_strike_chance_PlusPercent_vs_bleeding_enemies(PlusPercentage(f32)),
    attack_damage_PlusPercent_for_4_seconds_on_cast(PlusPercentage(f32)),
    physical_attack_damage_PlusPercent(PlusPercentage(f32)),
    map_pinnacle_boss_item_dropped_rarity_PlusPercent_final(PlusPercentage(f32)),
    aftershock_area_of_effect_PlusPercent(PlusPercentage(f32)),
    culling_strike_threshold_PlusPercent(PlusPercentage(f32)),
    trap_damage_PlusPercent(PlusPercentage(f32)),
    stun_threshold_PlusPercent_when_not_stunned_recently(PlusPercentage(f32)),
    curse_effect_on_self_PlusPercent(PlusPercentage(f32)),
    stun_threshold_PlusPercent_during_empowered_attacks(PlusPercentage(f32)),
    map_delirium_daemon_damage_PlusPercent(PlusPercentage(f32)),
    totem_damage_PlusPercent(PlusPercentage(f32)),
    quiver_mod_effect_PlusPercent(PlusPercentage(f32)),
    damage_vs_shocked_enemies_PlusPercent(PlusPercentage(f32)),
    melee_hit_damage_stun_multiplier_PlusPercent(PlusPercentage(f32)),
    global_gem_attribute_requirements_PlusPercent_final_from_gemling(PlusPercentage(f32)),
    map_boss_item_rarity_PlusPercent(PlusPercentage(f32)),
    offering_area_of_effect_PlusPercent(PlusPercentage(f32)),
    herald_skills_mana_reservation_PlusPercent(PlusPercentage(f32)),
    critical_strike_chance_while_dual_wielding_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_per_5_of_your_lowest_attribute(PlusPercentage(f32)),
    map_breach_monster_splinter_quantity_PlusPercent(PlusPercentage(f32)),
    recoup_speed_PlusPercent(PlusPercentage(f32)),
    triggered_spell_spell_damage_PlusPercent(PlusPercentage(f32)),
    accuracy_rating_PlusPercent_vs_enemies_in_close_range(PlusPercentage(f32)),
    map_gold_drop_chance_PlusPercent_in_mountain_biome(PlusPercentage(f32)),
    shock_effect_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_to_rare_and_unique_enemies(PlusPercentage(f32)),
    charm_charges_gained_PlusPercent(PlusPercentage(f32)),
    map_breach_chests_PlusPercent_final(PlusPercentage(f32)),
    energy_shield_from_focus_PlusPercent(PlusPercentage(f32)),
    ascendancy_titan_damage_reduction_rating_from_body_armour_PlusPercent_final(
        PlusPercentage(f32),
    ),
    map_expedition_fuse_burn_time_PlusPercent(PlusPercentage(f32)),
    map_ritual_deferred_rewards_are_offered_again_PlusPercent_sooner(PlusPercentage(f32)),
    sword_damage_PlusPercent(PlusPercentage(f32)),
    grenade_skill_damage_PlusPercent(PlusPercentage(f32)),
    life_regeneration_rate_PlusPercent(PlusPercentage(f32)),
    flask_mana_to_recover_PlusPercent(PlusPercentage(f32)),
    spell_skill_projectile_speed_PlusPercent(PlusPercentage(f32)),
    minion_damage_PlusPercent_while_you_have_at_least_two_different_active_offerings(
        PlusPercentage(f32),
    ),
    base_damaging_ailment_effect_PlusPercent(PlusPercentage(f32)),
    chill_and_freeze_duration_PlusPercent(PlusPercentage(f32)),
    map_expedition_elite_marker_count_PlusPercent(PlusPercentage(f32)),
    flail_attack_speed_PlusPercent(PlusPercentage(f32)),
    armour_PlusPercent_if_consumed_endurance_charge_recently(PlusPercentage(f32)),
    ailment_chance_PlusPercent(PlusPercentage(f32)),
    base_debuff_slow_magnitude_PlusPercent(PlusPercentage(f32)),
    reload_speed_PlusPercent(PlusPercentage(f32)),
    attack_speed_while_dual_wielding_PlusPercent(PlusPercentage(f32)),
    flask_life_recovery_rate_PlusPercent(PlusPercentage(f32)),
    charges_gained_PlusPercent(PlusPercentage(f32)),
    poison_effect_PlusPercent_vs_non_poisoned_enemies(PlusPercentage(f32)),
    offering_life_PlusPercent(PlusPercentage(f32)),
    base_frenzy_charge_duration_PlusPercent(PlusPercentage(f32)),
    map_delirium_doodads_PlusPercent_final(PlusPercentage(f32)),
    attack_speed_PlusPercent_if_you_have_not_attacked_recently(PlusPercentage(f32)),
    warcry_damage_PlusPercent(PlusPercentage(f32)),
    attack_and_cast_speed_PlusPercent(PlusPercentage(f32)),
    quarterstaff_hit_damage_freeze_multiplier_PlusPercent(PlusPercentage(f32)),
    movement_speed_PlusPercent_while_using_charm(PlusPercentage(f32)),
    claw_damage_PlusPercent(PlusPercentage(f32)),
    shock_chance_PlusPercent_vs_electrocuted_enemies(PlusPercentage(f32)),
    flask_life_and_mana_recovery_PlusPercent_while_using_charm(PlusPercentage(f32)),
    damage_PlusPercent_while_using_charm(PlusPercentage(f32)),
    hit_damage_PlusPercent_vs_ignited_enemies(PlusPercentage(f32)),
    poison_duration_PlusPercent_per_poison_applied_recently(PlusPercentage(f32)),
    melee_attack_speed_PlusPercent(PlusPercentage(f32)),
    claw_accuracy_rating_PlusPercent(PlusPercentage(f32)),
    map_affliction_reward_progress_on_kill_PlusPercent(PlusPercentage(f32)),
    accuracy_rating_while_dual_wielding_PlusPercent(PlusPercentage(f32)),
    maximum_energy_shield_PlusPercent(PlusPercentage(f32)),
    armour_PlusPercent_if_have_been_hit_recently(PlusPercentage(f32)),
    melee_damage_PlusPercent_when_on_full_life(PlusPercentage(f32)),
    skill_area_of_effect_PlusPercent_if_enemy_killed_recently(PlusPercentage(f32)),
    mana_regeneration_rate_PlusPercent(PlusPercentage(f32)),
    ailment_chance_PlusPercent_vs_rare_or_unique_enemy(PlusPercentage(f32)),
    one_handed_melee_attack_speed_PlusPercent(PlusPercentage(f32)),
    attack_speed_PlusPercent_while_surrounded(PlusPercentage(f32)),
    cast_speed_PlusPercent_when_on_full_life(PlusPercentage(f32)),
    mana_regeneration_rate_PlusPercent_while_not_on_low_mana(PlusPercentage(f32)),
    base_cast_speed_PlusPercent(PlusPercentage(f32)),
    flask_mana_charges_used_PlusPercent(PlusPercentage(f32)),
    movement_speed_PlusPercent_during_flask_effect(PlusPercentage(f32)),
    master_of_elements_evasion_rating_PlusPercent_final(PlusPercentage(f32)),
    buff_time_passed_PlusPercent_only_buff_category(PlusPercentage(f32)),
    elemental_damage_with_attack_skills_PlusPercent(PlusPercentage(f32)),
    life_regeneration_rate_PlusPercent_while_moving(PlusPercentage(f32)),
    bow_damage_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_per_15_strength(PlusPercentage(f32)),
    thorns_damage_PlusPercent_if_blocked_recently(PlusPercentage(f32)),
    base_ignite_effect_PlusPercent(PlusPercentage(f32)),
    minion_resummon_speed_PlusPercent(PlusPercentage(f32)),
    attack_and_cast_speed_PlusPercent_while_affected_by_a_mana_flask(PlusPercentage(f32)),
    map_map_item_drop_chance_PlusPercent(PlusPercentage(f32)),
    darkness_refresh_rate_PlusPercent(PlusPercentage(f32)),
    map_boss_experience_PlusPercent_final(PlusPercentage(f32)),
    damage_PlusPercent_per_1Percent_block_chance(PlusPercentage(f32)),
    minion_attack_and_cast_speed_PlusPercent(PlusPercentage(f32)),
    melee_critical_strike_chance_PlusPercent(PlusPercentage(f32)),
    spell_damage_PlusPercent(PlusPercentage(f32)),
    endurance_charge_duration_PlusPercent(PlusPercentage(f32)),
    empowered_attack_damage_PlusPercent(PlusPercentage(f32)),
    sorcery_ward_PlusPercent_strength(PlusPercentage(f32)),
    strength_PlusPercent(PlusPercentage(f32)),
    mana_recovery_rate_PlusPercent(PlusPercentage(f32)),
    mana_flask_charges_gained_PlusPercent(PlusPercentage(f32)),
    armour_evasion_PlusPercent_while_leeching(PlusPercentage(f32)),
    gemling_skill_cost_PlusPercent_final(PlusPercentage(f32)),
    projectile_damage_PlusPercent(PlusPercentage(f32)),
    map_ritual_rewards_reroll_cost_PlusPercent_final(PlusPercentage(f32)),
    map_socket_currency_drop_chance_PlusPercent_in_grass_biome(PlusPercentage(f32)),
    map_ritual_voodoo_king_key_chance_PlusPercent(PlusPercentage(f32)),
    damage_taken_PlusPercent_on_low_life(PlusPercentage(f32)),
    map_boss_maximum_life_PlusPercent(PlusPercentage(f32)),
    hinder_duration_PlusPercent(PlusPercentage(f32)),
    minion_life_recovery_rate_PlusPercent(PlusPercentage(f32)),
    totem_skill_attack_speed_PlusPercent(PlusPercentage(f32)),
    tablet_effect_PlusPercent_when_opening_a_map(PlusPercentage(f32)),
    map_ritual_monster_tankiness_PlusPercent_for_each_time_revived(PlusPercentage(f32)),
    withered_effect_PlusPercent(PlusPercentage(f32)),
    spell_area_damage_PlusPercent(PlusPercentage(f32)),
    energy_generated_PlusPercent(PlusPercentage(f32)),
    guard_flask_effect_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent(PlusPercentage(f32)),
    elemental_damage_PlusPercent_if_enemy_chilled_recently(PlusPercentage(f32)),
    witchhunter_armour_evasion_PlusPercent_final(PlusPercentage(f32)),
    critical_strike_chance_PlusPercent(PlusPercentage(f32)),
    armour_break_amount_PlusPercent_vs_enemies_affected_by_ailments(PlusPercentage(f32)),
    attack_damage_PlusPercent(PlusPercentage(f32)),
    cast_speed_PlusPercent_while_holding_staff(PlusPercentage(f32)),
    mana_regeneration_rate_PlusPercent_while_moving(PlusPercentage(f32)),
    map_player_shrine_effect_duration_PlusPercent(PlusPercentage(f32)),
    light_radius_PlusPercent(PlusPercentage(f32)),
    totems_spells_cast_speed_PlusPercent_per_active_totem(PlusPercentage(f32)),
    life_regeneration_rate_PlusPercent_while_on_low_life(PlusPercentage(f32)),
    evasion_rating_PlusPercent_while_you_have_energy_shield(PlusPercentage(f32)),
    elemental_damage_PlusPercent_if_have_crit_recently(PlusPercentage(f32)),
    mark_skill_duration_PlusPercent(PlusPercentage(f32)),
    flail_critical_strike_chance_PlusPercent(PlusPercentage(f32)),
    elemental_damage_PlusPercent(PlusPercentage(f32)),
    maximum_fire_damage_resistance_PlusPercent_per_40Percent_uncapped_fire_damage_resistance(
        PlusPercentage(f32),
    ),
    attack_critical_strike_chance_PlusPercent(PlusPercentage(f32)),
    map_delirium_boss_life_PlusPercent(PlusPercentage(f32)),
    spell_damage_PlusPercent_per_100_maximum_mana_up_to_60Percent(PlusPercentage(f32)),
    accuracy_rating_PlusPercent_vs_rare_or_unique_enemy(PlusPercentage(f32)),
    map_basic_currency_drop_chance_PlusPercent_in_swamp_and_water_biome(PlusPercentage(f32)),
    expedition_monsters_logbook_chance_PlusPercent(PlusPercentage(f32)),
    map_ritual_defer_reward_tribute_cost_PlusPercent(PlusPercentage(f32)),
    infernalist_critical_strike_multiplier_PlusPercent_final(PlusPercentage(f32)),
    map_breach_time_passed_PlusPercent(PlusPercentage(f32)),
    two_handed_melee_accuracy_rating_PlusPercent(PlusPercentage(f32)),
    intelligence_PlusPercent(PlusPercentage(f32)),
    evasion_rating_PlusPercent_if_energy_shield_recharge_started_in_past_2_seconds(
        PlusPercentage(f32),
    ),
    critical_hit_damage_bonus_PlusPercent_if_consumed_power_charge_recently(PlusPercentage(f32)),
    map_delirium_boss_splinter_amount_PlusPercent(PlusPercentage(f32)),
    empowered_attack_hit_damage_stun_multiplier_PlusPercent(PlusPercentage(f32)),
    quarterstaff_critical_strike_chance_PlusPercent(PlusPercentage(f32)),
    area_damage_PlusPercent(PlusPercentage(f32)),
    crossbow_damage_PlusPercent_per_ammo_type_fired_in_past_10_seconds(PlusPercentage(f32)),
    hit_damage_stun_multiplier_PlusPercent_vs_enemies_at_close_range(PlusPercentage(f32)),
    armour_break_amount_PlusPercent(PlusPercentage(f32)),
    dexterity_PlusPercent(PlusPercentage(f32)),
    map_mod_effect_PlusPercent_per_tower_affecting_area(PlusPercentage(f32)),
    global_defences_PlusPercent(PlusPercentage(f32)),
    enemies_cursed_by_you_have_life_regeneration_rate_PlusPercent(PlusPercentage(f32)),
    spirit_PlusPercent(PlusPercentage(f32)),
    titan_damage_PlusPercent_final_against_heavy_stunned_enemies(PlusPercentage(f32)),
    marked_enemy_accuracy_rating_PlusPercent(PlusPercentage(f32)),
    map_ritual_monster_spawning_speed_PlusPercent(PlusPercentage(f32)),
    warcry_skill_area_of_effect_PlusPercent(PlusPercentage(f32)),
    life_recovery_rate_PlusPercent(PlusPercentage(f32)),
    area_of_effect_PlusPercent_with_herald_skills(PlusPercentage(f32)),
    attack_speed_PlusPercent_if_enemy_killed_recently(PlusPercentage(f32)),
    base_mana_leech_amount_PlusPercent(PlusPercentage(f32)),
    bow_attack_speed_PlusPercent(PlusPercentage(f32)),
    block_chance_PlusPercent_if_blocked_with_active_block_recently(PlusPercentage(f32)),
    base_bleeding_effect_PlusPercent(PlusPercentage(f32)),
    ignite_duration_PlusPercent(PlusPercentage(f32)),
    power_charge_duration_PlusPercent(PlusPercentage(f32)),
    ice_crystal_maximum_life_PlusPercent(PlusPercentage(f32)),
    mana_recovery_rate_PlusPercent_while_affected_by_a_mana_flask(PlusPercentage(f32)),
    dagger_attack_speed_PlusPercent(PlusPercentage(f32)),
    grenade_skill_area_of_effect_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_while_wielding_wand(PlusPercentage(f32)),
    mastery_chance_to_evade_melee_attacks_PlusPercent_final(PlusPercentage(f32)),
    heavy_stun_poise_decay_rate_PlusPercent(PlusPercentage(f32)),
    base_cost_PlusPercent(PlusPercentage(f32)),
    critical_strike_chance_PlusPercent_if_have_not_crit_recently(PlusPercentage(f32)),
    ascendancy_pathfinder_flask_charges_gained_PlusPercent_final(PlusPercentage(f32)),
    map_tower_augment_quantity_PlusPercent(PlusPercentage(f32)),
    mace_hit_damage_stun_multiplier_PlusPercent(PlusPercentage(f32)),
    lightning_exposure_effect_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_with_one_handed_weapons(PlusPercentage(f32)),
    while_curse_is_50Percent_expired_curse_effect_PlusPercent(PlusPercentage(f32)),
    energy_shield_recovery_rate_PlusPercent(PlusPercentage(f32)),
    critical_strike_chance_PlusPercent_if_enemy_killed_recently(PlusPercentage(f32)),
    curse_effect_PlusPercent(PlusPercentage(f32)),
    spell_critical_strike_chance_PlusPercent(PlusPercentage(f32)),
    map_expedition_rare_monsters_PlusPercent(PlusPercentage(f32)),
    base_bleed_duration_PlusPercent(PlusPercentage(f32)),
    lightning_damage_PlusPercent_per_10_intelligence(PlusPercentage(f32)),
    cast_speed_for_cold_skills_PlusPercent(PlusPercentage(f32)),
    evasion_rating_PlusPercent_if_you_dodge_rolled_recently(PlusPercentage(f32)),
    map_mod_effect_PlusPercent_per_mod(PlusPercentage(f32)),
    rage_decay_speed_PlusPercent(PlusPercentage(f32)),
    daze_build_up_PlusPercent(PlusPercentage(f32)),
    attack_damage_PlusPercent_when_on_full_life(PlusPercentage(f32)),
    sword_attack_speed_PlusPercent(PlusPercentage(f32)),
    evasion_rating_PlusPercent_if_consumed_frenzy_charge_recently(PlusPercentage(f32)),
    area_of_effect_PlusPercent_if_enemy_stunned_with_two_handed_melee_weapon_recently(
        PlusPercentage(f32),
    ),
    final_repeat_of_spells_area_of_effect_PlusPercent(PlusPercentage(f32)),
    hit_damage_PlusPercent_vs_enemies_affected_by_ailments(PlusPercentage(f32)),
    map_item_drop_rarity_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_vs_dazed_enemies(PlusPercentage(f32)),
    placing_traps_cooldown_recovery_PlusPercent(PlusPercentage(f32)),
    stun_threshold_PlusPercent_when_on_full_life(PlusPercentage(f32)),
    dagger_damage_PlusPercent(PlusPercentage(f32)),
    quarterstaff_hit_damage_stun_multiplier_PlusPercent(PlusPercentage(f32)),
    critical_hit_bleeding_effect_PlusPercent(PlusPercentage(f32)),
    one_handed_attack_ailment_chance_PlusPercent(PlusPercentage(f32)),
    ignite_chance_PlusPercent(PlusPercentage(f32)),
    base_slow_potency_PlusPercent(PlusPercentage(f32)),
    attack_and_cast_speed_PlusPercent_on_placing_totem(PlusPercentage(f32)),
    map_affliction_encounter_boss_chance_PlusPercent(PlusPercentage(f32)),
    energy_shield_PlusPercent_if_consumed_power_charge_recently(PlusPercentage(f32)),
    spell_staff_damage_PlusPercent(PlusPercentage(f32)),
    physical_damage_PlusPercent(PlusPercentage(f32)),
    attack_area_of_effect_PlusPercent(PlusPercentage(f32)),
    map_jewel_drop_chance_PlusPercent_in_forest_biome(PlusPercentage(f32)),
    attack_and_cast_speed_PlusPercent_with_lightning_skills(PlusPercentage(f32)),
    movement_speed_PlusPercent_if_cast_a_mark_spell_recently(PlusPercentage(f32)),
    base_poison_duration_PlusPercent(PlusPercentage(f32)),
    attack_mana_cost_PlusPercent(PlusPercentage(f32)),
    stun_threshold_PlusPercent_per_number_of_times_stunned_recently(PlusPercentage(f32)),
    stormweaver_shock_duration_PlusPercent_final(PlusPercentage(f32)),
    life_recovery_PlusPercent_from_flasks_while_on_low_life(PlusPercentage(f32)),
    minion_accuracy_rating_PlusPercent(PlusPercentage(f32)),
    evasion_rating_PlusPercent_if_you_have_hit_an_enemy_recently(PlusPercentage(f32)),
    passive_tree_mace_damage_PlusPercent_final_vs_heavy_stunned_enemies(PlusPercentage(f32)),
    attack_area_damage_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_if_you_have_consumed_a_corpse_recently(PlusPercentage(f32)),
    damage_PlusPercent_while_totem_active(PlusPercentage(f32)),
    movement_speed_PlusPercent_while_you_have_energy_shield(PlusPercentage(f32)),
    evasion_rating_PlusPercent_if_have_not_been_hit_recently(PlusPercentage(f32)),
    minion_maximum_life_PlusPercent(PlusPercentage(f32)),
    all_attributes_PlusPercent(PlusPercentage(f32)),
    unarmed_attack_speed_PlusPercent(PlusPercentage(f32)),
    flail_damage_PlusPercent(PlusPercentage(f32)),
    movement_speed_PlusPercent_if_pinned_enemy_recently(PlusPercentage(f32)),
    minion_cooldown_recovery_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_with_herald_skills(PlusPercentage(f32)),
    curse_area_of_effect_PlusPercent(PlusPercentage(f32)),
    critical_strike_chance_PlusPercent_vs_shocked_enemies(PlusPercentage(f32)),
    base_stun_recovery_PlusPercent(PlusPercentage(f32)),
    map_pack_size_PlusPercent(PlusPercentage(f32)),
    blind_effect_PlusPercent(PlusPercentage(f32)),
    attack_speed_PlusPercent_while_holding_shield(PlusPercentage(f32)),
    attack_speed_PlusPercent_during_flask_effect(PlusPercentage(f32)),
    attack_damage_PlusPercent_while_ally_in_presence(PlusPercentage(f32)),
    damage_PlusPercent_per_enemy_elemental_ailment(PlusPercentage(f32)),
    pathfinder_poison_duration_PlusPercent_final(PlusPercentage(f32)),
    damage_PlusPercent_vs_burning_enemies(PlusPercentage(f32)),
    maximum_mana_PlusPercent(PlusPercentage(f32)),
    map_ritual_omen_chance_PlusPercent(PlusPercentage(f32)),
    aura_effect_PlusPercent(PlusPercentage(f32)),
    small_passives_effect_PlusPercent(PlusPercentage(f32)),
    spell_damage_PlusPercent_while_es_full(PlusPercentage(f32)),
    flask_charges_used_PlusPercent(PlusPercentage(f32)),
    map_ritual_daemon_damage_PlusPercent(PlusPercentage(f32)),
    warcry_speed_PlusPercent(PlusPercentage(f32)),
    charm_duration_PlusPercent(PlusPercentage(f32)),
    crossbow_attack_speed_PlusPercent(PlusPercentage(f32)),
    shield_evasion_rating_PlusPercent(PlusPercentage(f32)),
    elemental_storm_cooldown_recovery_speed_PlusPercent_final(PlusPercentage(f32)),
    map_ritual_magic_monsters_PlusPercent(PlusPercentage(f32)),
    map_mod_effect_PlusPercent(PlusPercentage(f32)),
    spear_damage_PlusPercent(PlusPercentage(f32)),
    base_skill_area_of_effect_PlusPercent(PlusPercentage(f32)),
    hit_damage_stun_multiplier_PlusPercent(PlusPercentage(f32)),
    fire_exposure_effect_PlusPercent(PlusPercentage(f32)),
    critical_strike_chance_against_enemies_on_full_life_PlusPercent(PlusPercentage(f32)),
    chill_effectiveness_on_self_PlusPercent(PlusPercentage(f32)),
    life_flask_charges_gained_PlusPercent(PlusPercentage(f32)),
    deadeye_movement_speed_penalty_PlusPercent_final_while_performing_action(PlusPercentage(f32)),
    attack_speed_PlusPercent_if_have_been_hit_recently(PlusPercentage(f32)),
    grenade_skill_cooldown_speed_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_while_affected_by_a_herald(PlusPercentage(f32)),
    attack_damage_PlusPercent_per_75_armour_or_evasion_on_shield(PlusPercentage(f32)),
    base_all_ailment_duration_on_self_PlusPercent(PlusPercentage(f32)),
    dagger_critical_strike_chance_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_per_different_warcry_used_recently(PlusPercentage(f32)),
    maximum_life_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_per_active_curse_on_self(PlusPercentage(f32)),
    accuracy_rating_PlusPercent(PlusPercentage(f32)),
    evasion_rating_PlusPercent_when_on_full_life(PlusPercentage(f32)),
    flask_life_to_recover_PlusPercent(PlusPercentage(f32)),
    hit_damage_electrocute_multiplier_PlusPercent(PlusPercentage(f32)),
    mark_skill_cast_speed_PlusPercent(PlusPercentage(f32)),
    projectile_ailment_chance_PlusPercent(PlusPercentage(f32)),
    defences_PlusPercent_while_wielding_staff(PlusPercentage(f32)),
    curse_delay_PlusPercent(PlusPercentage(f32)),
    arcane_surge_effect_on_self_PlusPercent(PlusPercentage(f32)),
    jagged_ground_effect_PlusPercent(PlusPercentage(f32)),
    base_life_leech_amount_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_vs_enemies_on_full_life(PlusPercentage(f32)),
    freeze_threshold_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_vs_hindered_enemies(PlusPercentage(f32)),
    critical_strike_chance_PlusPercent_vs_enemies_with_lightning_exposure(PlusPercentage(f32)),
    maximum_life_mana_and_energy_shield_PlusPercent(PlusPercentage(f32)),
    attack_speed_PlusPercent_per_200_accuracy_rating(PlusPercentage(f32)),
    body_armour_evasion_rating_PlusPercent(PlusPercentage(f32)),
    base_cooldown_speed_PlusPercent(PlusPercentage(f32)),
    hit_damage_electrocute_multiplier_PlusPercent_vs_shocked_enemies(PlusPercentage(f32)),
    fire_damage_PlusPercent_while_affected_by_herald_of_ash(PlusPercentage(f32)),
    map_item_drop_quantity_PlusPercent(PlusPercentage(f32)),
    projectile_damage_PlusPercent_vs_enemies_further_than_6m_distance(PlusPercentage(f32)),
    trap_throwing_speed_PlusPercent(PlusPercentage(f32)),
    attack_damage_vs_bleeding_enemies_PlusPercent(PlusPercentage(f32)),
    jagged_ground_enemy_damage_taken_PlusPercent(PlusPercentage(f32)),
    chronomancer_every_8_seconds_PlusPercent_final_cast_speed_for_4_seconds(PlusPercentage(f32)),
    maximum_darkness_PlusPercent(PlusPercentage(f32)),
    base_curse_duration_PlusPercent(PlusPercentage(f32)),
    spell_critical_strike_chance_PlusPercent_while_wielding_staff(PlusPercentage(f32)),
    damaging_ailments_deal_damage_PlusPercent_faster(PlusPercentage(f32)),
    mana_regeneration_rate_PlusPercent_if_enemy_shocked_recently(PlusPercentage(f32)),
    minion_critical_strike_chance_PlusPercent(PlusPercentage(f32)),
    ascendancy_energy_generated_PlusPercent_final(PlusPercentage(f32)),
    minion_damage_PlusPercent(PlusPercentage(f32)),
    ailment_threshold_PlusPercent(PlusPercentage(f32)),
    evasion_and_physical_damage_reduction_rating_PlusPercent(PlusPercentage(f32)),
    chill_duration_PlusPercent(PlusPercentage(f32)),
    minion_evasion_rating_PlusPercent(PlusPercentage(f32)),
    map_affliction_secondary_wave_acceleration_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_against_enemies_with_fully_broken_armour(PlusPercentage(f32)),
    skill_area_of_effect_when_unarmed_PlusPercent(PlusPercentage(f32)),
    quarterstaff_attack_speed_PlusPercent(PlusPercentage(f32)),
    trap_critical_strike_chance_PlusPercent(PlusPercentage(f32)),
    critical_hit_damaging_ailment_effect_PlusPercent(PlusPercentage(f32)),
    map_magic_chest_amount_PlusPercent(PlusPercentage(f32)),
    movement_speed_PlusPercent_while_dual_wielding(PlusPercentage(f32)),
    stun_threshold_PlusPercent(PlusPercentage(f32)),
    critical_strike_chance_PlusPercent_vs_enemies_without_elemental_status_ailments(
        PlusPercentage(f32),
    ),
    damage_PlusPercent_with_daggers_against_full_life_enemies(PlusPercentage(f32)),
    damage_vs_enemies_on_low_life_PlusPercent(PlusPercentage(f32)),
    map_ritual_rare_monsters_PlusPercent(PlusPercentage(f32)),
    mana_cost_PlusPercent_while_not_low_mana(PlusPercentage(f32)),
    link_skill_buff_effect_PlusPercent(PlusPercentage(f32)),
    critical_strike_chance_PlusPercent_vs_enemies_further_than_6m_distance(PlusPercentage(f32)),
    crossbow_damage_PlusPercent(PlusPercentage(f32)),
    ignite_shock_chill_duration_PlusPercent(PlusPercentage(f32)),
    armour_PlusPercent_while_surrounded(PlusPercentage(f32)),
    deadeye_projectile_damage_PlusPercent_final_max_as_distance_travelled_increases(
        PlusPercentage(f32),
    ),
    spear_attack_speed_PlusPercent(PlusPercentage(f32)),
    critical_strike_chance_PlusPercent_vs_dazed_enemies(PlusPercentage(f32)),
    map_boss_damage_PlusPercent(PlusPercentage(f32)),
    totem_placement_range_PlusPercent(PlusPercentage(f32)),
    axe_attack_speed_PlusPercent(PlusPercentage(f32)),
    block_chance_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_vs_frozen_enemies(PlusPercentage(f32)),
    mana_regeneration_rate_PlusPercent_while_stationary(PlusPercentage(f32)),
    map_player_damage_taken_PlusPercent_vs_breach_monsters(PlusPercentage(f32)),
    marked_enemy_damage_taken_PlusPercent(PlusPercentage(f32)),
    map_magic_pack_size_PlusPercent(PlusPercentage(f32)),
    deadeye_projectile_damage_PlusPercent_final_max_as_distance_travelled_decreases(
        PlusPercentage(f32),
    ),
    witchhunter_up_to_damage_PlusPercent_final_against_targets_with_missing_focus(
        PlusPercentage(f32),
    ),
    projectile_hit_damage_stun_multiplier_PlusPercent(PlusPercentage(f32)),
    minion_movement_speed_PlusPercent(PlusPercentage(f32)),
    link_skill_cast_speed_PlusPercent(PlusPercentage(f32)),
    map_ritual_monster_damage_PlusPercent_for_each_time_revived(PlusPercentage(f32)),
    cast_speed_PlusPercent_for_4_seconds_on_attack(PlusPercentage(f32)),
    quarterstaff_accuracy_rating_PlusPercent(PlusPercentage(f32)),
    offering_duration_PlusPercent(PlusPercentage(f32)),
    freeze_duration_PlusPercent(PlusPercentage(f32)),
    claw_critical_strike_chance_PlusPercent(PlusPercentage(f32)),
    flask_effect_PlusPercent(PlusPercentage(f32)),
    cold_exposure_effect_PlusPercent(PlusPercentage(f32)),
    energy_shield_recharge_rate_PlusPercent(PlusPercentage(f32)),
    elemental_damage_PlusPercent_if_enemy_ignited_recently(PlusPercentage(f32)),
    enemies_in_presence_cooldown_recovery_PlusPercent(PlusPercentage(f32)),
    witch_passive_maximum_lightning_damage_PlusPercent_final(PlusPercentage(f32)),
    hit_damage_stun_multiplier_PlusPercent_vs_enemies_on_low_life(PlusPercentage(f32)),
    map_player_shrine_buff_effect_on_self_PlusPercent(PlusPercentage(f32)),
    map_number_of_rare_packs_PlusPercent(PlusPercentage(f32)),
    daze_duration_PlusPercent(PlusPercentage(f32)),
    damaging_ailment_duration_PlusPercent(PlusPercentage(f32)),
    stormweaver_chill_effect_PlusPercent_final(PlusPercentage(f32)),
    grenade_fuse_duration_PlusPercent(PlusPercentage(f32)),
    global_item_attribute_requirements_PlusPercent(PlusPercentage(f32)),
    shock_chance_PlusPercent(PlusPercentage(f32)),
    critical_hit_ignite_effect_PlusPercent(PlusPercentage(f32)),
    mark_effect_PlusPercent(PlusPercentage(f32)),
    damage_taken_PlusPercent_final_per_tailwind(PlusPercentage(f32)),
    damage_PlusPercent_with_two_handed_weapons(PlusPercentage(f32)),
    map_number_of_magic_packs_PlusPercent(PlusPercentage(f32)),
    chill_effect_PlusPercent(PlusPercentage(f32)),
    shock_duration_PlusPercent(PlusPercentage(f32)),
    non_damaging_ailment_effect_PlusPercent(PlusPercentage(f32)),
    link_skill_duration_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_if_triggered_skill_recently(PlusPercentage(f32)),
    shield_armour_PlusPercent(PlusPercentage(f32)),
    attack_damage_PlusPercent_while_surrounded(PlusPercentage(f32)),
    flask_duration_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_for_4_seconds_on_crit(PlusPercentage(f32)),
    body_armour_PlusPercent(PlusPercentage(f32)),
    attack_damage_PlusPercent_vs_rare_or_unique_enemy(PlusPercentage(f32)),
    slam_skill_area_of_effect_PlusPercent(PlusPercentage(f32)),
    mark_skill_mana_cost_PlusPercent(PlusPercentage(f32)),
    damage_PlusPercent_while_unarmed(PlusPercentage(f32)),
    ailment_effect_PlusPercent(PlusPercentage(f32)),
    crossbow_critical_strike_chance_PlusPercent(PlusPercentage(f32)),
    spell_area_of_effect_PlusPercent(PlusPercentage(f32)),
    base_projectile_speed_PlusPercent(PlusPercentage(f32)),
    titan_maximum_life_PlusPercent_final(PlusPercentage(f32)),
    life_regeneration_rate_PlusPercent_while_using_life_flask(PlusPercentage(f32)),
    melee_damage_PlusPercent(PlusPercentage(f32)),
    map_expedition_artifact_quantity_PlusPercent(PlusPercentage(f32)),
    notable_knockback_distance_PlusPercent_final_for_blocked_hits(PlusPercentage(f32)),
    // non_skill_base_lightning_damage_Percent_to_gain_as_cold(Other(f32)),
    // evasion_rating_Percent_to_gain_as_armour(Other(f32)),
    // link_skills_can_target_minions(Other(f32)),
    // base_attack_damage_penetrates_elemental_resist_Percent(Other(f32)),
    // map_tier_bonus_permillage(Other(f32)),
    // base_dexterity(Other(f32)),
    // map_breach_hands_inflict_waking_nightmare(Other(f32)),
    // base_darkness_refresh_rate_ms(Other(f32)),
    // evasion_rating_also_reduces_physical_damage(Other(f32)),
    // grenade_skill_Percent_chance_to_explode_twice(Other(f32)),
    // damage_removed_from_your_nearest_totem_before_life_or_es_Percent(Other(f32)),
    // recover_Percent_maximum_life_on_killing_poisoned_enemy(Other(f32)),
    // mace_strike_aftershock_chance_Percent(Other(f32)),
    // gain_tailwind_stack_on_skill_use(Other(f32)),
    // trigger_skills_refund_half_energy_spent_chance_Percent(Other(f32)),
    // focus_decay_Percent_per_minute(Other(f32)),
    // lose_Percent_of_life_and_energy_shield_when_you_use_a_chaos_skill(Other(f32)),
    // aggravate_bleeding_when_inflicted_vs_enemies_on_jagged_ground_chance_Percent(Other(f32)),
    // damage_with_hits_is_lucky_vs_enemies_on_low_life(Other(f32)),
    // attack_additional_critical_strike_chance_permyriad(Other(f32)),
    // all_damage_can_shock(Other(f32)),
    // minion_damage_taken_Percent_recouped_as_their_life(Other(f32)),
    // additional_critical_strike_chance_permyriad_with_herald_skills(Other(f32)),
    // map_pinnacle_boss_rare_socket_currency_chance_Percent(Other(f32)),
    // blind_enemies_when_they_stun_you(Other(f32)),
    // minion_maximum_all_elemental_resistances_Percent(Other(f32)),
    // base_maximum_life(Other(f32)),
    // titan_expanded_main_inventory(Other(f32)),
    // life_regeneration_rate_per_minute_Percent_when_on_low_life(Other(f32)),
    // map_ritual_contains_wildwood_wisp(Other(f32)),
    // max_demon_form_stacks(Other(f32)),
    // gain_accuracy_rating_equal_to_strength(Other(f32)),
    // additional_all_attributes(Other(f32)),
    // lose_Percent_of_infernal_flame_on_reaching_max(Other(f32)),
    // double_tablet_effect_chance_Percent_when_opening_a_map(Other(f32)),
    // area_skill_knockback_chance_Percent(Other(f32)),
    // map_breach_rares_catalyst_full_stack_chance_Percent(Other(f32)),
    // lightning_skill_additional_chain_chance_Percent(Other(f32)),
    // hits_ignore_elemental_resistances_vs_frozen_enemies(Other(f32)),
    // defend_with_Percent_armour_against_attacks_from_distance_greater_than_6m(Other(f32)),
    // Percent_maximum_life_as_focus(Other(f32)),
    // life_regeneration_rate_per_minute_Percent_if_used_life_flask_in_past_10_seconds(Other(f32)),
    // convert_all_life_leech_to_energy_shield_leech(Other(f32)),
    // heavy_stuns_have_culling_strike(Other(f32)),
    // life_gained_on_block(Other(f32)),
    // resolute_technique(Other(f32)),
    // fire_exposure_you_inflict_lowers_fire_resistance_by_extra_Percent(Other(f32)),
    // keystone_ancestral_bond(Other(f32)),
    // crossbow_attack_Percent_chance_to_not_consume_ammo(Other(f32)),
    // recover_Percent_maximum_mana_on_charm_use(Other(f32)),
    // pathfinder_ascendancy_poison_on_enemies_you_kill_spread_to_enemies_within_x(Other(f32)),
    // base_aggravate_bleeding_on_attack_hit_chance_Percent(Other(f32)),
    // map_maps_drop_with_distilled_emotions_applied_chance_Percent(Other(f32)),
    // map_breach_chests_drop_double_splinters_chance_Percent(Other(f32)),
    // ascendancy_chronomancer_apex_of_the_moment_base_slow_aura_value(Other(f32)),
    // map_breach_Percent_chance_for_3_additional_breach(Other(f32)),
    // restore_life_and_mana_on_warcry_Percent(Other(f32)),
    // gain_x_rage_when_hit(Other(f32)),
    // recover_Percent_life_per_endurance_charge_consumed(Other(f32)),
    // minion_fire_damage_resistance_Percent(Other(f32)),
    // gain_max_rage_on_rage_gain_from_hit_Percent_chance(Other(f32)),
    // minion_maximum_life_Percent_to_gain_as_maximum_energy_shield(Other(f32)),
    // quarterstaff_skills_that_consume_power_charges_count_as_consuming_x_additional_power_charges(Other(f32)),
    // world_map_unique_maps_visible_X_units_beyond_light_radius(Other(f32)),
    // mace_slam_aftershock_chance_Percent(Other(f32)),
    // ascendancy_beidats_hand_energy_shield_Plus_per_X_maximum_life(Other(f32)),
    // critical_damage_Plus1Percent_per_X_current_life(Other(f32)),
    // map_pinnacle_boss_special_gem_drop_chance_Percent(Other(f32)),
    // base_evasion_rating(Other(f32)),
    // warcry_empowers_next_x_melee_attacks(Other(f32)),
    // keystone_bulwark(Other(f32)),
    // maim_on_hit_Percent(Other(f32)),
    // totems_regenerate_Percent_life_per_minute(Other(f32)),
    // base_intelligence(Other(f32)),
    // stun_threshold_Plus_from_Percent_maximum_energy_shield(Other(f32)),
    // minion_additional_physical_damage_reduction_Percent(Other(f32)),
    // recover_Percent_maximum_life_on_kill(Other(f32)),
    // map_expedition_x_extra_relic_suffixes(Other(f32)),
    // gain_arcane_surge_on_crit_Percent_chance(Other(f32)),
    // evasion_rating_Plus_per_1_helmet_energy_shield(Other(f32)),
    // maximum_cold_resistance_Plus1_per_X_corresponding_support(Other(f32)),
    // recover_Percent_maximum_life_on_mana_flask_use(Other(f32)),
    // charms_Percent_chance_on_use_to_use_another_charm_without_consuming_charges(Other(f32)),
    // unaffected_by_chill_during_dodge_roll(Other(f32)),
    // maps_boss_drop_additional_bonus_map_chance_Percent(Other(f32)),
    // map_delirium_difficulty_scaling_from_mirror_is_double(Other(f32)),
    // damage_with_hits_is_lucky_vs_heavy_stunned_enemies(Other(f32)),
    // gemling_double_basic_attribute_bonuses(Other(f32)),
    // base_cold_damage_resistance_Percent(Other(f32)),
    // map_expedition_x_extra_relic_prefixes(Other(f32)),
    // non_skill_base_all_damage_Percent_to_gain_as_fire(Other(f32)),
    // allies_in_presence_life_regeneration_rate_per_minute_equal_to_your_maximum_life_Percent(Other(f32)),
    // keystone_chaos_inoculation(Other(f32)),
    // base_darkness(Other(f32)),
    // infernal_flame_instead_of_mana(Other(f32)),
    // recover_Percent_maximum_mana_on_kill(Other(f32)),
    // max_jade_stacks(Other(f32)),
    // physical_damage_taken_recouped_as_life_Percent(Other(f32)),
    // cannot_be_blinded_while_on_full_life(Other(f32)),
    // minion_lightning_damage_resistance_Percent(Other(f32)),
    // defend_with_Percent_of_armour_while_not_on_low_energy_shield(Other(f32)),
    // map_shrine_chance_Percent(Other(f32)),
    // enemies_chaos_resistance_Percent_while_cursed(Other(f32)),
    // enemies_you_curse_have_15Percent_hinder(Other(f32)),
    // gain_accuracy_rating_equal_to_intelligence(Other(f32)),
    // keystone_blood_magic(Other(f32)),
    // gain_endurance_charge_on_heavy_stunning_rare_or_unique_enemy(Other(f32)),
    // gain_unbound_ailment_stacks(Other(f32)),
    // marked_enemies_cannot_deal_critical_strikes(Other(f32)),
    // base_maximum_mana(Other(f32)),
    // hellhound_takes_Percent_damage_before_you(Other(f32)),
    // base_maximum_energy_shield(Other(f32)),
    // map_pinnacle_boss_drops_X_waystones(Other(f32)),
    // aggravate_bleeding_on_attack_crit_chance_Percent(Other(f32)),
    // charms_Percent_chance_to_not_consume_charges(Other(f32)),
    // map_breach_chance_to_be_guarded_by_magic_pack_Percent(Other(f32)),
    // base_maximum_cold_damage_resistance_Percent(Other(f32)),
    // keystone_dance_with_death(Other(f32)),
    // ancestral_slam_every_other_slam(Other(f32)),
    // base_body_armour_permyriad_to_gain_as_physical_thorns_damage(Other(f32)),
    // max_endurance_charges(Other(f32)),
    // inflict_fire_exposure_on_hits_that_heavy_stun(Other(f32)),
    // life_regeneration_rate_per_minute_Percent_while_surrounded(Other(f32)),
    // drain_focus_Percent_of_damage_dealt_on_hit(Other(f32)),
    // Plus1_spirit_per_X_energy_shield_on_body_armour(Other(f32)),
    // keystone_avatar_of_fire(Other(f32)),
    // cold_hit_and_dot_damage_Percent_taken_as_fire(Other(f32)),
    // hit_Percent_chance_to_gain_100Percent_damage_as_chaos(Other(f32)),
    // enemies_are_maimed_for_x_seconds_after_becoming_unpinned(Other(f32)),
    // keystone_hex_master(Other(f32)),
    // can_apply_additional_chill(Other(f32)),
    // curses_never_expire(Other(f32)),
    // base_maximum_lightning_damage_resistance_Percent(Other(f32)),
    // gain_maximum_power_charges_on_power_charge_gained_Percent_chance(Other(f32)),
    // crushing_blow(Other(f32)),
    // can_block_all_hits_while_shield_is_lowered(Other(f32)),
    // non_skill_base_physical_damage_Percent_to_gain_as_fire(Other(f32)),
    // damage_taken_goes_to_mana_Percent(Other(f32)),
    // refresh_ignite_duration_on_critical_strike_chance_Percent(Other(f32)),
    // hit_Percent_chance_to_gain_50Percent_damage_as_chaos(Other(f32)),
    // cold_exposure_you_inflict_lowers_cold_resistance_by_extra_Percent(Other(f32)),
    // ascendancy_beidats_gaze_mana_Plus_per_X_maximum_life(Other(f32)),
    // all_damage_can_chill(Other(f32)),
    // base_maximum_chaos_damage_resistance_Percent(Other(f32)),
    // base_chance_to_poison_on_hit_Percent(Other(f32)),
    // buildup_jade_every_x_ms(Other(f32)),
    // minion_accuracy_rating(Other(f32)),
    // life_regeneration_rate_per_minute_Percent_if_have_been_hit_recently(Other(f32)),
    // additional_physical_damage_reduction_Percent_per_jade(Other(f32)),
    // you_and_allies_in_presence_non_skill_base_all_damage_Percent_to_gain_as_fire_while_on_high_infernal_flame(Other(f32)),
    // additive_armour_modifiers_apply_to_energy_shield_recharge_rate_at_Percent_value(Other(f32)),
    // accuracy_rating_vs_bleeding_enemies(Other(f32)),
    // ailment_threshold_Plus_from_lowest_of_base_boots_evasion_rating_and_armour(Other(f32)),
    // chaos_damage_resistance_is_doubled(Other(f32)),
    // map_pinnacle_boss_drops_X_corrupted_rare_tablets(Other(f32)),
    // critical_strikes_ignore_positive_elemental_resistances(Other(f32)),
    // additional_maximum_all_elemental_resistances_Percent(Other(f32)),
    // life_reserved_by_stat_Percent(Other(f32)),
    // armour_Plus_from_Percent_strength_requirements_from_boots_gloves_helmets(Other(f32)),
    // chance_for_skills_to_avoid_cooldown_Percent(Other(f32)),
    // chance_Percent_to_double_effect_of_removing_frenzy_charges(Other(f32)),
    // bleed_on_crit_Percent(Other(f32)),
    // chance_to_gain_onslaught_on_kill_with_axes_Percent(Other(f32)),
    // minion_chaos_resistance_Percent(Other(f32)),
    // map_pinnacle_boss_additional_unique_drop_chance_Percent(Other(f32)),
    // infernalist_burn_life_and_es_Percent_per_second_if_crit_recently(Other(f32)),
    // base_thorns_critical_strike_chance(Other(f32)),
    // focus_decay_delay_ms(Other(f32)),
    // maximum_life_Percent_to_gain_as_maximum_energy_shield(Other(f32)),
    // maximum_lightning_resistance_Plus1_per_X_corresponding_support(Other(f32)),
    // gain_x_rage_on_hit_with_axes(Other(f32)),
    // aggravate_bleeding_older_than_ms_on_hit(Other(f32)),
    // knockback_on_crit_with_quarterstaff(Other(f32)),
    // base_maximum_fire_damage_resistance_Percent(Other(f32)),
    // evasion_rating_Plus_per_1_armour_on_gloves(Other(f32)),
    // witchhunter_chance_to_explode_enemies_for_100Percent_of_life_as_physical(Other(f32)),
    // lightning_penetration_Percent_while_on_low_mana(Other(f32)),
    // energy_shield_gained_on_block(Other(f32)),
    // gain_maximum_endurance_charges_on_endurance_charge_gained_Percent_chance(Other(f32)),
    // minion_cold_damage_resistance_Percent(Other(f32)),
    // deadeye_accuracy_unaffected_by_range(Other(f32)),
    // reduce_enemy_elemental_resistance_Percent(Other(f32)),
    // keystone_acrobatics(Other(f32)),
    // corpses_in_your_presence_explode_dealing_Percent_maximum_life_physical_damage_on_warcry(Other(f32)),
    // map_breach_Percent_chance_for_10_additional_breach(Other(f32)),
    // gain_Percent_damage_as_chaos_from_unreserved_darkness(Other(f32)),
    // base_chance_to_pierce_Percent(Other(f32)),
    // stun_threshold_Plus_per_strength(Other(f32)),
    // flasks_Percent_chance_to_not_consume_charges(Other(f32)),
    // gain_maximum_frenzy_charges_on_frenzy_charge_gained_Percent_chance(Other(f32)),
    // culling_strike_vs_marked_enemy(Other(f32)),
    // keystone_iron_reflexes(Other(f32)),
    // chance_to_poison_on_critical_strike_with_dagger_Percent(Other(f32)),
    // map_delirium_additional_reward_type_chance_Percent(Other(f32)),
    // physical_damage_from_hits_Percent_taken_as_random_element(Other(f32)),
    // arcane_surge_effect_Plus1Percent_per_X_maximum_mana(Other(f32)),
    // Plus1_spirit_per_X_evasion_rating_on_body_armour(Other(f32)),
    // maps_with_bosses_are_irradiated(Other(f32)),
    // darkness_per_level(Other(f32)),
    // recoup_Percent_elemental_damage_as_energy_shield(Other(f32)),
    // recover_X_life_on_block(Other(f32)),
    // lose_Percent_of_life_loss_over_4_seconds_instead(Other(f32)),
    // map_breach_Percent_chance_for_1_additional_breach(Other(f32)),
    // maximum_mana_Percent_gained_on_kill(Other(f32)),
    // base_should_have_arcane_surge_from_stat(Other(f32)),
    // can_apply_additional_shock(Other(f32)),
    // keystone_zealots_oath(Other(f32)),
    // map_expiditon_logbooks_drop_with_3_implicits(Other(f32)),
    // rage_loss_delay_ms(Other(f32)),
    // enemies_near_marked_enemy_are_blinded(Other(f32)),
    // global_chance_to_blind_on_hit_Percent(Other(f32)),
    // num_additional_skill_slots(Other(f32)),
    // chance_to_double_armour_effect_on_hit_Percent(Other(f32)),
    // non_skill_base_all_damage_Percent_to_gain_as_lightning(Other(f32)),
    // chance_to_fork_extra_projectile_Percent(Other(f32)),
    // life_remnants_gain_per_globe(Other(f32)),
    // minions_get_amulet_stats_instead_of_you(Other(f32)),
    // base_reduce_enemy_lightning_resistance_Percent(Other(f32)),
    // arrow_base_number_of_targets_to_pierce(Other(f32)),
    // inflict_withered_for_x_seconds_on_unwithered_enemies_when_they_enter_your_presence(Other(f32)),
    // spell_skills_fire_2_additional_projectiles_final_chance_Percent(Other(f32)),
    // totem_elemental_resistance_Percent(Other(f32)),
    // minion_elemental_resistance_Percent(Other(f32)),
    // double_number_of_poison_you_can_inflict(Other(f32)),
    // xPercent_faster_start_of_sorcery_ward_recovery(Other(f32)),
    // base_life_gained_on_enemy_death(Other(f32)),
    // life_regeneration_rate_per_minute_Percent_while_affected_by_damaging_ailment(Other(f32)),
    // slows_have_no_potency_on_you(Other(f32)),
    // atlas_keystone_extreme_archaeology(Other(f32)),
    // accuracy_rating(Other(f32)),
    // number_of_additional_projectiles(Other(f32)),
    // minions_deal_Percent_of_physical_damage_as_additional_chaos_damage(Other(f32)),
    // exposure_you_inflict_lowers_affected_resistance_by_extra_Percent(Other(f32)),
    // generate_x_charges_for_life_flasks_per_minute(Other(f32)),
    // every_4_seconds_regenerate_Percent_of_armour_and_evasion_as_life_over_1_second(Other(f32)),
    // chance_Percent_to_create_shocking_ground_on_shock(Other(f32)),
    // base_life_leech_does_not_stop_at_full_life(Other(f32)),
    // keystone_eldritch_battery(Other(f32)),
    // mana_gained_on_block(Other(f32)),
    // knockback_chance_Percent_at_close_range(Other(f32)),
    // totem_additional_physical_damage_reduction_Percent(Other(f32)),
    // base_reduce_enemy_fire_resistance_Percent(Other(f32)),
    // shock_enemies_in_150cm_radius_on_shock_chance_Percent(Other(f32)),
    // map_final_boss_map_key_of_at_least_same_tier_as_current_map_drop_chance_Percent(Other(f32)),
    // elementalist_chill_maximum_magnitude_override(Other(f32)),
    // keystone_heartstopper(Other(f32)),
    // while_using_sword_reduce_enemy_block_Percent(Other(f32)),
    // base_reduce_enemy_cold_resistance_Percent(Other(f32)),
    // minions_gain_your_dexterity(Other(f32)),
    // you_gain_Percent_life_when_one_of_your_minions_is_revived(Other(f32)),
    // map_duplicate_x_rare_monsters(Other(f32)),
    // recover_Percent_life_when_you_create_an_offering(Other(f32)),
    // max_power_charges(Other(f32)),
    // projectile_chance_to_chain_1_extra_time_from_terrain_Percent(Other(f32)),
    // allies_in_presence_accuracy_rating(Other(f32)),
    // keystone_glancing_blows(Other(f32)),
    // critical_strike_multiplier_Plus_if_have_not_dealt_critical_strike_recently(Other(f32)),
    // number_of_infernal_familiars_allowed(Other(f32)),
    // non_skill_base_all_damage_Percent_to_gain_as_cold(Other(f32)),
    // keystone_pain_attunement(Other(f32)),
    // maximum_rage(Other(f32)),
    // critical_strike_multiplier_Plus_if_have_dealt_non_crit_recently(Other(f32)),
    // hit_Percent_chance_to_gain_25Percent_damage_as_chaos(Other(f32)),
    // faster_burn_Percent(Other(f32)),
    // critical_strike_multiplier_Plus_vs_burning_enemies(Other(f32)),
    // skill_cost_base_life_equal_to_base_mana(Other(f32)),
    // generate_x_charges_for_mana_flasks_per_minute(Other(f32)),
    // recoup_effects_apply_over_4_seconds_instead(Other(f32)),
    // keystone_conduit(Other(f32)),
    // max_frenzy_charges(Other(f32)),
    // warbringer_overbreak_armour(Other(f32)),
    // kill_enemy_on_hit_if_under_10Percent_life(Other(f32)),
    // base_penetrate_elemental_resistances_Percent(Other(f32)),
    // decimating_strike(Other(f32)),
    // base_physical_damage_reduction_rating(Other(f32)),
    // map_monolith_chance_Percent(Other(f32)),
    // defend_with_Percent_armour_against_critical_strikes(Other(f32)),
    // explode_burning_enemies_for_10Percent_life_as_fire_on_kill_chance_Percent(Other(f32)),
    // physical_damage_prevented_recouped_as_life_Percent(Other(f32)),
    // base_chance_to_poison_on_hit_Percent_vs_non_poisoned_enemies(Other(f32)),
    // base_fire_damage_resistance_Percent(Other(f32)),
    // lose_Percent_of_max_infernal_flame_per_minute(Other(f32)),
    // chance_to_summon_two_totems_Percent(Other(f32)),
    // life_flask_effects_are_not_removed_at_full_life(Other(f32)),
    // life_regenerate_rate_per_second_Percent_while_totem_active(Other(f32)),
    // base_life_leech_from_all_spell_damage_permyriad(Other(f32)),
    // keystone_giants_blood(Other(f32)),
    // life_regeneration_rate_per_minute_Percent_while_stationary(Other(f32)),
    // mana_leech_applies_recovery_to_energy_shield_also(Other(f32)),
    // trigger_wild_strike_on_attack_crit(Other(f32)),
    // arrow_speed_additive_modifiers_also_apply_to_bow_damage(Other(f32)),
    // bleed_on_crit_Percent_with_attacks(Other(f32)),
    // keystone_oasis(Other(f32)),
    // map_boss_area_chance_to_be_corrupted_Percent(Other(f32)),
    // breach_flame_effects_doubled(Other(f32)),
    // you_and_allies_in_presence_all_damage_can_ignite_while_not_on_low_infernal_flame(Other(f32)),
    // map_ritual_additional_reward_rerolls(Other(f32)),
    // ascendancy_beidats_will_spirit_Plus_per_X_maximum_life(Other(f32)),
    // maximum_rage_Plus_while_wielding_axe(Other(f32)),
    // non_skill_base_all_damage_Percent_to_gain_as_chaos(Other(f32)),
    // maximum_energy_shield_Plus1_per_x_body_armour_evasion_rating(Other(f32)),
    // armour_break_Percent_of_armour_on_heavy_stunning(Other(f32)),
    // armour_break_damage_Percent_dealt_as_armour_break(Other(f32)),
    // number_of_additional_poison_stacks(Other(f32)),
    // link_to_X_additional_random_allies(Other(f32)),
    // base_mana_leech_is_instant(Other(f32)),
    // recover_Percent_mana_when_you_invoke_a_spell(Other(f32)),
    // create_chilling_ground_on_freeze(Other(f32)),
    // keystone_vaal_pact(Other(f32)),
    // stun_threshold_Plus_from_Percent_base_armour_from_equipment(Other(f32)),
    // critical_strike_multiplier_Plus_vs_stunned_enemies(Other(f32)),
    // faster_bleed_Percent(Other(f32)),
    // recover_maximum_life_on_enemy_killed_chance_Percent(Other(f32)),
    // base_dexterity_and_intelligence(Other(f32)),
    // base_chance_to_not_consume_corpse_Percent(Other(f32)),
    // map_ritual_encounter_count_is_four(Other(f32)),
    // enemies_you_curse_cannot_recharge_energy_shield(Other(f32)),
    // reapply_enemy_shock_on_consuming_enemy_shock_chance_Percent(Other(f32)),
    // atlas_keystone_rare_or_unique_monsters_have_1_or_2_additional_mods(Other(f32)),
    // gain_guard_flask_charge_when_hit_by_enemy_chance_Percent(Other(f32)),
    // trigger_elemental_storm_on_crit(Other(f32)),
    // gem_requirements_can_be_satisfied_by_highest_attribute(Other(f32)),
    // number_of_additional_marks_allowed(Other(f32)),
    // recover_Percent_life_on_heavy_stunning_rare_or_unique_enemy(Other(f32)),
    // extra_damage_rolls_with_lightning_damage_on_non_critical_hits(Other(f32)),
    // map_strongbox_chance_Percent(Other(f32)),
    // display_passive_attribute_text(Other(f32)),
    // attacks_chance_to_blind_on_hit_Percent(Other(f32)),
    // cannot_gain_spirit_from_equipment(Other(f32)),
    // non_skill_base_physical_damage_Percent_to_gain_as_chaos(Other(f32)),
    // grenade_skill_number_of_additional_projectiles(Other(f32)),
    // critical_strike_multiplier_Plus_during_any_flask_effect(Other(f32)),
    // defend_with_Percent_armour_against_ranged_attacks(Other(f32)),
    // warcries_bypass_cooldown(Other(f32)),
    // atlas_keystone_corruption_roulette(Other(f32)),
    // unaffected_by_chill_while_mana_leeching(Other(f32)),
    // base_armour_Percent_applies_to_fire_damage(Other(f32)),
    // spawn_defender_with_totem(Other(f32)),
    // armour_break_equal_to_Percent_physical_damage_dealt_on_critical_strike_with_spells(Other(f32)),
    // ailment_threshold_Plus_per_dexterity(Other(f32)),
    // minions_have_Percent_chance_to_inflict_wither_on_hit(Other(f32)),
    // leech_Percent_is_instant(Other(f32)),
    // base_chaos_damage_resistance_Percent(Other(f32)),
    // block_chance_from_equipped_shield_is_Percent(Other(f32)),
    // spell_critical_strike_multiplier_Plus_while_wielding_staff(Other(f32)),
    // map_killing_rare_monsters_pauses_delirium_mirror_timer_for_x_seconds(Other(f32)),
    // keystone_unwavering_stance(Other(f32)),
    // damage_taken_goes_to_life_mana_es_over_4_seconds_Percent(Other(f32)),
    // aggravate_bleeding_on_exerted_attack_hit_chance_Percent(Other(f32)),
    // base_resist_all_elements_Percent(Other(f32)),
    // lightning_hit_and_dot_damage_Percent_taken_as_fire(Other(f32)),
    // stun_threshold_Plus_from_lowest_of_base_helmet_evasion_rating_and_armour(Other(f32)),
    // elemental_damage_can_inflict_bleeding(Other(f32)),
    // base_chance_to_inflict_bleeding_Percent(Other(f32)),
    // generate_x_charges_for_charms_per_minute(Other(f32)),
    // base_skill_cost_life_instead_of_mana_Percent(Other(f32)),
    // life_regeneration_rate_per_minute_Percent(Other(f32)),
    // elemental_damage_taken_Percent_recouped_as_life(Other(f32)),
    // map_ritual_additional_daemon(Other(f32)),
    // physical_hit_and_dot_damage_Percent_taken_as_chaos(Other(f32)),
    // dummy_stat_display_nothing(Other(f32)),
    // damage_taken_goes_to_life_over_4_seconds_Percent(Other(f32)),
    // map_essence_monsters_chance_for_2_additional_essences_Percent(Other(f32)),
    // cannot_have_more_than_1_damaging_ailment(Other(f32)),
    // non_skill_cold_damage_Percent_to_gain_as_fire_vs_frozen_enemies(Other(f32)),
    // stun_threshold_based_on_Percent_energy_shield_instead_of_life(Other(f32)),
    // recover_Percent_life_when_you_use_a_life_flask_while_on_low_life(Other(f32)),
    // map_expedition_chests_despawn_after_X_seconds(Other(f32)),
    // minion_life_regeneration_rate_per_minute_Percent(Other(f32)),
    // base_strength(Other(f32)),
    // lose_all_tailwind_when_hit(Other(f32)),
    // critical_strike_multiplier_Plus_if_gained_power_charge_recently(Other(f32)),
    // keystone_mana_shield(Other(f32)),
    // regenerate_Percent_life_over_1_second_when_stunned(Other(f32)),
    // keystone_eternal_youth(Other(f32)),
    // gain_Percent_life_from_body_es(Other(f32)),
    // maim_on_hit_Percent_vs_poisoned_enemies(Other(f32)),
    // base_strength_and_intelligence(Other(f32)),
    // base_spell_critical_strike_chance_override_permyriad(Other(f32)),
    // base_strength_and_dexterity(Other(f32)),
    // map_ritual_no_revive_penalty(Other(f32)),
    // attack_skills_additional_totems_allowed(Other(f32)),
    // remove_curse_on_mana_flask_use(Other(f32)),
    // non_skill_base_all_damage_Percent_to_gain_as_physical(Other(f32)),
    // cannot_recharge_energy_shield(Other(f32)),
    // projectile_chance_to_piece_vs_enemies_within_3m_distance_of_player(Other(f32)),
    // gain_x_rage_on_melee_hit(Other(f32)),
    // hit_for_Percent_max_life_es_on_max_infernal_flame(Other(f32)),
    // base_damage_removed_from_mana_before_life_Percent(Other(f32)),
    // slam_aftershock_chance_Percent(Other(f32)),
    // keystone_elemental_equilibrium(Other(f32)),
    // base_block_Percent_damage_taken(Other(f32)),
    // num_charm_slots(Other(f32)),
    // keystone_charge_cycle(Other(f32)),
    // map_breach_rares_have_soul_eater(Other(f32)),
    // maximum_fire_resistance_Plus1_per_X_corresponding_support(Other(f32)),
    // map_ritual_additional_wildwood_packs(Other(f32)),
}
