[package]
name = "poo-tools"
version = "0.1.0"
edition = "2021"
[[bin]]
path = "src/main.rs"
name = "vis"


[[bin]]
path = "src/tree_utils.rs"
name = "tree"

[dependencies]
anyhow = "1.0.95"
bevy = "0.15.1"
chrono = { version = "0.4.39", features = ["serde"] }
clap = { version = "4.5.23", features = ["derive"] }
colored = "2.2.0"
egui = "0.30.0"
ggez = "0.9.3"
iced = "0.13.1"
log = "0.4.22"
pretty_env_logger = "0.5.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
serde_yaml = "0.9.34"
toml = "0.8.19"
