[package]
name = "poo-visualiser"
version = "0.1.0"
edition = "2021"

[dependencies]
poo_tree = { workspace = true }
log.workspace = true
egui.workspace = true
eframe.workspace = true
pretty_env_logger.workspace = true
