[package]
name = "poo_tree"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
anyhow = { workspace = true }
colored = { workspace = true }
eframe = { workspace = true }
egui = { workspace = true }
log = { workspace = true }
pretty_env_logger = { workspace = true }
rfd = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
toml = { workspace = true }
