#$ crates/poe_tree/Cargo.toml
[package]
name = "poe_tree"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { workspace = true }
egui = { workspace = true }
log = { workspace = true }
pretty_env_logger = { workspace = true }
rfd = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
toml = { workspace = true }
chrono = { workspace = true, features = ["serde"]}
